# SwiftLint Configuration for SecureDesk
# https://github.com/realm/SwiftLint

# Paths to include
included:
  - SecureDesk

# Paths to exclude
excluded:
  - SecureDesk.xcodeproj
  - DerivedData
  - .build

# Enabled rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - yoda_condition

# Disabled rules
disabled_rules:
  - trailing_whitespace
  - todo
  - opening_brace
  - attributes  # Conflicts with SwiftUI inline @Environment
  - pattern_matching_keywords  # Common Swift pattern
  - trailing_closure  # Sometimes explicit is clearer
  - redundant_type_annotation  # Explicit types can be helpful

# Custom rule configurations
line_length:
  warning: 120
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 600
  error: 1000

type_body_length:
  warning: 400
  error: 600

function_body_length:
  warning: 60
  error: 100

function_parameter_count:
  warning: 8
  error: 10

type_name:
  min_length: 3
  max_length: 50

identifier_name:
  min_length: 2
  max_length: 50
  excluded:
    - id
    - x
    - y
    - z
    - i
    - j
    - to

nesting:
  type_level: 3
  function_level: 5

cyclomatic_complexity:
  warning: 15
  error: 25

# File header template
file_header:
  required_pattern: |
    \/\/
    \/\/  .*\.swift
    \/\/  SecureDesk
    \/\/
    \/\/  Created by .*
    \/\/

# Reporter type
reporter: "xcode"
